export const API = {
  BASE_PATH: process.env.REACT_APP_BASE_API_URL,
  USER_SIGNIN: "/auth/signin",
  USER_SIGNUP: "/auth/signup",
};

export const ACTION_TYPES = {
  UPDATE_SIGNUP_STATUS: "UPDATE_SIGNUP_STATUS",
  UPDATE_AUTH_STATUS: "UPDATE_AUTH_STATUS",
  AUTH_API_ERROR: "AUTH_API_ERROR",
};
